export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SET_USER = "SET_USER";
export const SAVE_UID = "SAVE_UID";
export const PASSWORD_RESET_INITIATE = "PASSWORD_RESET_INITIATE";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PROFILE_UPDATE_INIT = "PROFILE_UPDATE_INIT";

export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";

export const PROFILE_UPDATE_Fail = "PROFILE_UPDATE_Fail";
export const PROFILE_PICTURE_UPLOAD_SUCCESS = "PROFILE_PICTURE_UPLOAD_SUCCESS";

export const JOB_POST_INIT = "JOB_POST_INIT";
export const JOB_POST_SUCCESS = "JOB_POST_SUCCESS"
export const JOB_POST_FAIL = "JOB_POST_FAIL"
// export const GET_ALL_JOB_INIT = "GET_ALL_JOB_INIT"
// export const GET_ALL_JOB_SUCCESS = "GET_ALL_JOB_SUCCESS"
export const JOB_UPDATE_INIT = "JOB_UPDATE_INIT"
export const JOB_UPDATE_SUCCESS = "JOB_UPDATE_SUCCESS"
export const JOB_UPDATE_FAIL = "JOB_UPDATE_FAIL"
export const JOB_DELETE_INIT = "JOB_DELETE_INIT"
export const JOB_DELETE_SUCCESS = "JOB_DELETE_SUCCESS"
export const GET_ALL_JOB = "GET_ALL_JOB"
export const GET_APPLIED_STUDENTS = "GET_APPLIED_STUDENTS"
export const REMOVE_APPLIED_STUDENT = "REMOVE_APPLIED_STUDENT"
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS"
export const APPLIED_JOBS_GET_SUCCESS = "APPLIED_JOBS_GET_SUCCESS"
export const STUDENTS_ARRAYS = "STUDENTS_ARRAYS"
export const APPROVAL_SUCCESS_STUDENTS = "APPROVAL_SUCCESS_STUDENTS"
export const APPROVAL_SUCCESS_COMPANIES = "APPROVAL_SUCCESS_COMPANIES"
export const COMPANIES_ARRAYS = "COMPANIES_ARRAYS"
export const COMPANY_BLOCKED_OR_UNBLOCK_SUCCESS = "COMPANY_BLOCKED_OR_UNBLOCK_SUCCESS"
export const STUDENT_BLOCKED_OR_UNBLOCK_SUCCESS = "STUDENT_BLOCKED_OR_UNBLOCK_SUCCESS"
export const USER_BLOCK_AND_UNBLOCK = "USER_BLOCK_AND_UNBLOCK"